/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiV1SmsSendRouteImport } from './routes/api/v1/sms/send'
import { Route as ApiPublicV1GatewayHeartbeatRouteImport } from './routes/api/public/v1/gateway/heartbeat'
import { Route as ApiPublicV1GatewayPairRouteImport } from './routes/api/public/v1/gateway/pair'
import { Route as ApiPublicV1SmsSendRouteImport } from './routes/api/public/v1/sms/send'
import { Route as ApiPublicV1GatewayJobsAckRouteImport } from './routes/api/public/v1/gateway/jobs/ack'
import { Route as ApiPublicV1GatewayJobsClaimRouteImport } from './routes/api/public/v1/gateway/jobs/claim'
import { Route as ApiPublicV1SmsStatusMessageIdRouteImport } from './routes/api/public/v1/sms/status.$messageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SmsSendRoute = ApiV1SmsSendRouteImport.update({
  id: '/api/v1/sms/send',
  path: '/api/v1/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1GatewayHeartbeatRoute =
  ApiPublicV1GatewayHeartbeatRouteImport.update({
    id: '/api/public/v1/gateway/heartbeat',
    path: '/api/public/v1/gateway/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1GatewayPairRoute = ApiPublicV1GatewayPairRouteImport.update({
  id: '/api/public/v1/gateway/pair',
  path: '/api/public/v1/gateway/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SmsSendRoute = ApiPublicV1SmsSendRouteImport.update({
  id: '/api/public/v1/sms/send',
  path: '/api/public/v1/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1GatewayJobsAckRoute =
  ApiPublicV1GatewayJobsAckRouteImport.update({
    id: '/api/public/v1/gateway/jobs/ack',
    path: '/api/public/v1/gateway/jobs/ack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1GatewayJobsClaimRoute =
  ApiPublicV1GatewayJobsClaimRouteImport.update({
    id: '/api/public/v1/gateway/jobs/claim',
    path: '/api/public/v1/gateway/jobs/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SmsStatusMessageIdRoute =
  ApiPublicV1SmsStatusMessageIdRouteImport.update({
    id: '/api/public/v1/sms/status/$messageId',
    path: '/api/public/v1/sms/status/$messageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/gateway': typeof GatewayRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/v1/sms/send': typeof ApiV1SmsSendRoute
  '/api/public/v1/gateway/heartbeat': typeof ApiPublicV1GatewayHeartbeatRoute
  '/api/public/v1/gateway/pair': typeof ApiPublicV1GatewayPairRoute
  '/api/public/v1/sms/send': typeof ApiPublicV1SmsSendRoute
  '/api/public/v1/gateway/jobs/ack': typeof ApiPublicV1GatewayJobsAckRoute
  '/api/public/v1/gateway/jobs/claim': typeof ApiPublicV1GatewayJobsClaimRoute
  '/api/public/v1/sms/status/$messageId': typeof ApiPublicV1SmsStatusMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/gateway': typeof GatewayRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/v1/sms/send': typeof ApiV1SmsSendRoute
  '/api/public/v1/gateway/heartbeat': typeof ApiPublicV1GatewayHeartbeatRoute
  '/api/public/v1/gateway/pair': typeof ApiPublicV1GatewayPairRoute
  '/api/public/v1/sms/send': typeof ApiPublicV1SmsSendRoute
  '/api/public/v1/gateway/jobs/ack': typeof ApiPublicV1GatewayJobsAckRoute
  '/api/public/v1/gateway/jobs/claim': typeof ApiPublicV1GatewayJobsClaimRoute
  '/api/public/v1/sms/status/$messageId': typeof ApiPublicV1SmsStatusMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/gateway': typeof GatewayRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/v1/sms/send': typeof ApiV1SmsSendRoute
  '/api/public/v1/gateway/heartbeat': typeof ApiPublicV1GatewayHeartbeatRoute
  '/api/public/v1/gateway/pair': typeof ApiPublicV1GatewayPairRoute
  '/api/public/v1/sms/send': typeof ApiPublicV1SmsSendRoute
  '/api/public/v1/gateway/jobs/ack': typeof ApiPublicV1GatewayJobsAckRoute
  '/api/public/v1/gateway/jobs/claim': typeof ApiPublicV1GatewayJobsClaimRoute
  '/api/public/v1/sms/status/$messageId': typeof ApiPublicV1SmsStatusMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/gateway'
    | '/api-keys'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/settings'
    | '/api/public/v1/health'
    | '/api/v1/sms/send'
    | '/api/public/v1/gateway/heartbeat'
    | '/api/public/v1/gateway/pair'
    | '/api/public/v1/sms/send'
    | '/api/public/v1/gateway/jobs/ack'
    | '/api/public/v1/gateway/jobs/claim'
    | '/api/public/v1/sms/status/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/gateway'
    | '/api-keys'
    | '/dashboard'
    | '/devices'
    | '/logs'
    | '/settings'
    | '/api/public/v1/health'
    | '/api/v1/sms/send'
    | '/api/public/v1/gateway/heartbeat'
    | '/api/public/v1/gateway/pair'
    | '/api/public/v1/sms/send'
    | '/api/public/v1/gateway/jobs/ack'
    | '/api/public/v1/gateway/jobs/claim'
    | '/api/public/v1/sms/status/$messageId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/gateway'
    | '/_authenticated/api-keys'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/logs'
    | '/_authenticated/settings'
    | '/api/public/v1/health'
    | '/api/v1/sms/send'
    | '/api/public/v1/gateway/heartbeat'
    | '/api/public/v1/gateway/pair'
    | '/api/public/v1/sms/send'
    | '/api/public/v1/gateway/jobs/ack'
    | '/api/public/v1/gateway/jobs/claim'
    | '/api/public/v1/sms/status/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  GatewayRoute: typeof GatewayRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiV1SmsSendRoute: typeof ApiV1SmsSendRoute
  ApiPublicV1GatewayHeartbeatRoute: typeof ApiPublicV1GatewayHeartbeatRoute
  ApiPublicV1GatewayPairRoute: typeof ApiPublicV1GatewayPairRoute
  ApiPublicV1SmsSendRoute: typeof ApiPublicV1SmsSendRoute
  ApiPublicV1GatewayJobsAckRoute: typeof ApiPublicV1GatewayJobsAckRoute
  ApiPublicV1GatewayJobsClaimRoute: typeof ApiPublicV1GatewayJobsClaimRoute
  ApiPublicV1SmsStatusMessageIdRoute: typeof ApiPublicV1SmsStatusMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sms/send': {
      id: '/api/v1/sms/send'
      path: '/api/v1/sms/send'
      fullPath: '/api/v1/sms/send'
      preLoaderRoute: typeof ApiV1SmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/gateway/heartbeat': {
      id: '/api/public/v1/gateway/heartbeat'
      path: '/api/public/v1/gateway/heartbeat'
      fullPath: '/api/public/v1/gateway/heartbeat'
      preLoaderRoute: typeof ApiPublicV1GatewayHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/gateway/pair': {
      id: '/api/public/v1/gateway/pair'
      path: '/api/public/v1/gateway/pair'
      fullPath: '/api/public/v1/gateway/pair'
      preLoaderRoute: typeof ApiPublicV1GatewayPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sms/send': {
      id: '/api/public/v1/sms/send'
      path: '/api/public/v1/sms/send'
      fullPath: '/api/public/v1/sms/send'
      preLoaderRoute: typeof ApiPublicV1SmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/gateway/jobs/ack': {
      id: '/api/public/v1/gateway/jobs/ack'
      path: '/api/public/v1/gateway/jobs/ack'
      fullPath: '/api/public/v1/gateway/jobs/ack'
      preLoaderRoute: typeof ApiPublicV1GatewayJobsAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/gateway/jobs/claim': {
      id: '/api/public/v1/gateway/jobs/claim'
      path: '/api/public/v1/gateway/jobs/claim'
      fullPath: '/api/public/v1/gateway/jobs/claim'
      preLoaderRoute: typeof ApiPublicV1GatewayJobsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sms/status/$messageId': {
      id: '/api/public/v1/sms/status/$messageId'
      path: '/api/public/v1/sms/status/$messageId'
      fullPath: '/api/public/v1/sms/status/$messageId'
      preLoaderRoute: typeof ApiPublicV1SmsStatusMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  GatewayRoute: GatewayRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiV1SmsSendRoute: ApiV1SmsSendRoute,
  ApiPublicV1GatewayHeartbeatRoute: ApiPublicV1GatewayHeartbeatRoute,
  ApiPublicV1GatewayPairRoute: ApiPublicV1GatewayPairRoute,
  ApiPublicV1SmsSendRoute: ApiPublicV1SmsSendRoute,
  ApiPublicV1GatewayJobsAckRoute: ApiPublicV1GatewayJobsAckRoute,
  ApiPublicV1GatewayJobsClaimRoute: ApiPublicV1GatewayJobsClaimRoute,
  ApiPublicV1SmsStatusMessageIdRoute: ApiPublicV1SmsStatusMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
